### ISSUE TITLE
RATIO

### ISSUE THREAD

**Issue by LeleDerGrasshalmi** [RobinOfiONIZUKA/ONIZUKAFN-DLL-SOURCE-CODE#1]
ratio
![image](https://user-images.githubusercontent.com/62852525/160925097-851cccde-64df-46d1-810c-5e87440cbaec.png)

**Comment by RobinOfiONIZUKA** [comment]
Before this source was used by almost all the servers of FN, Aurora, Rocket, Storm, Onizukafn, Kratozukafn
